yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
]

yatube/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordResetDoneView,
                                       PasswordResetCompleteView)

from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'),
        name='password_change_done'
    ),
    path(
        'password_change/', views.CustomPasswordChangeView.as_view(
            template_name='users/password_change_form.html'),
        name='password_change_form'),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'),
        name='password_reset_complete'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'),
        name='password_reset_done'
    ),
    path(
        'reset/<str:uidb64>/<str:token>/',
        views.CustomPasswordConfirmView.as_view(
            template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'
    ),
    path(
        'password_reset/', views.CustomPasswordResetView.as_view(
            template_name='users/password_reset_form.html'),
        name='password_reset_form'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name='Текст',
                            help_text='Введите текст поста')
    pub_date = models.DateTimeField(auto_now_add=True,
                                    verbose_name='Дата публикации')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='posts',
                               verbose_name='Автор')
    group = models.ForeignKey(
        Group, blank=True, null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name_plural = "Посты"

    def __str__(self):
        return self.text[:15]

yatube/posts/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group')

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Group, User
from django.conf import settings
from .forms import PostForm


def index(request):
    posts = Post.objects.all()
    paginator = Paginator(posts, settings.POSTS_COUNT)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    paginator = Paginator(posts, settings.POSTS_COUNT)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'posts': posts,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = author.posts.all()
    paginator = Paginator(post_list, settings.POSTS_COUNT)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    posts_count = author.posts.count()
    context = {
        'author': author,
        'page_obj': page_obj,
        'posts': post_list,
        'posts_count': posts_count,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    posts_count = post.author.posts.count()
    context = {
        'post': post,
        'posts_count': posts_count,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', post.author.username)
    return render(request, 'posts/post_create.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    is_edit = True
    form = PostForm(request.POST, instance=post)
    if post.author != request.user:
        return redirect('posts:post_detail', post.id)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    context = {
        'is_edit': is_edit,
        'form': form,
        'post': post
    }
    return render(request, 'posts/post_create.html', context)

yatube/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import CreationForm
from django.contrib.auth.views import (PasswordChangeView,
                                       PasswordResetConfirmView,
                                       PasswordResetView)


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'


class CustomPasswordChangeView(PasswordChangeView):
    success_url = reverse_lazy('users:password_change_done')


class CustomPasswordResetView(PasswordResetView):
    success_url = reverse_lazy('users:password_reset_done')


class CustomPasswordConfirmView(PasswordResetConfirmView):
    success_url = reverse_lazy('users:password_reset_complete')

yatube/templates/about/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
<h1>Привет, меня зовут Мария Тумилович.</h1>
<p>
    В данный момент я обучаюсь на Python разработчика в Яндексе (я уже имею базовые знания написания кода на Python и SQL(учусь около года помимо текущего курса), работала с Git, знаю принципы ООП, изучаю сейчас HTML, Django). 
    До этого в этом году прошла два курса по повышению квалификации: аналитик данных и тестировщик ПО. 
    В сфере тестирования имею опыт функционального и нефункционального тестирования сайтов, написания чек-листов, тест-кейсов, баг-репортов и отчётов по проведенному тестированию, а также имею опыт проведения автотестов с помощью Selenium IDE, написанию базовых запросов на SQL. 
    В сфере аналитики данных работала на Python с различными библиотеками для машинного обучения(numpy, scipy, sklearn, seaborn, pandas) в google.collaboratory и в knime.

    Ссылка на мой github: https://github.com/khamaran
</p>
{% endblock %} 

yatube/templates/about/tech.html
<!-- templates/about/tech.html -->
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
{% comment %} Колонки с отступом сверху и снизу {% endcomment %}
<div class="row">
  <h1>Вот что я умею</h1>
  {% comment %}
    Боковой блок со списком технологий 
    Займет всю ширину блока на мобильном
    и 25% при размерах экрана ≥768px
  {% endcomment %}
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Python
      </li>
      <li class="list-group-item">
        Django
      </li>
    </ul>
  </aside>
  {% comment %}
    Статья  
    Займет всю ширину блока на мобильном
    и 75% при размерах экрана ≥768px
  {% endcomment %}
  <article class="col-12 col-md-9">
    <p>Текст страницы "Технологии"</p>
  </article>
</div>
{% endblock %}

yatube/templates/base.html
{% load static %}


<!DOCTYPE html> 
<html lang="ru"> 
  <head>    
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> 
    <meta charset="utf-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script> 
    
    
    <title>
      {% block title %}
        Последние обновления на сайте
      {% endblock %}
    </title>
  </head>
  <body>
  
  
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main> 

    
    {% block content %}
        Контент не подвезли!
    {% endblock %}

    
    </main>       
    <footer class="border-top text-center py-3">
      {% include 'includes/footer.html' %} 
    </footer>
  </body>
</html>

yatube/templates/includes/footer.html
<!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
<p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>  

yatube/templates/includes/header.html
{% load static %}

  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
      {% comment %}
      Меню - список пунктов со стандартными классами Bootsrap.
      Класс nav-pills нужен для выделения активных пунктов 
      {% endcomment %}
      <ul class="nav nav-pills">
      {% with request.resolver_match.view_name as view_name %} 
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}" href="{% url 'about:author' %}">Об авторе</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}" href="{% url 'about:tech' %}">Технологии</a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}" href="{% url 'posts:post_create' %}">Новая запись</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:password_change_form' %}active{% endif %}" href="{% url 'users:password_change_form' %}">Изменить пароль</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:logout' %}active{% endif %}" href="{% url 'users:logout' %}">Выйти</a>
        </li>
        <li>
          Пользователь: {{ user.username }}
        </li>
        {% else %}
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:login' %}active{% endif %}" href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}" href="{% url 'users:signup' %}">Регистрация</a>
        </li>
        {% endif %}
        {% endwith %} 
      </ul>
    </div>
  </nav>      

yatube/templates/includes/paginator.html
{% load static %}


{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}
 

yatube/templates/posts/group_list.html
{% extends 'base.html' %}


{% block title %}Записи сообщества {{ group.title }}{% endblock %}


{% block content %}
      <div class="container py-5">
        <h1>{{ group }}</h1>
        <p>{{ group.description }}</p>    
          {% for post in posts %}
          <article>
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>      
          <p>{{ post.text }}</p> 
        <article>
        {% if not forloop.last %}<hr>{% endif %}
        {% endfor %} 
      </div>   
      {% include 'includes/paginator.html' %}
{% endblock %} 

yatube/templates/posts/index.html
{% extends 'base.html' %}


{% block title %}Последние обновления на сайте{% endblock %}


{% block content %}
<div class="container py-5">     
  <h1>Это главная страница проекта Yatube</h1>  
{% for post in page_obj %}
  <article>
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  <p>{{ post.text }}</p>   
  {% if post.group %}   
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
  {% endif %} 
  </article>
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %} 
</div>  

  {% include 'includes/paginator.html' %}
{% endblock %} 

yatube/templates/posts/post_create.html
{% extends 'base.html' %}

{% block title %}{% if is_edit %} Редактировать запись {% else %} Добавить запись {% endif %}{% endblock %}

{% block content %}
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">    
                {% if is_edit %}
                  Редактировать пост
                {% else %}
                  Новый пост
                {% endif %}                  
              </div>
              <div class="card-body"> 
                {% if form.errors %}
                 {% for field in form %}
              {% for error in field.errors %}            
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}     
          {% if is_edit %}  
                <form method="post" action="{% url 'posts:post_edit' post.id %}">
          {% else %}
                <form method="post" action="{% url 'posts:post_create' %}">
          {% endif %}
                    {% csrf_token %}
                    {% for field in form %} 
                  <div class="form-group row my-3 p-3">
                    <label for="{{ field.id_for_label }}">
                        {{ field.label }}
                        {% if field.field.required %}          
                      <span class="required text-danger" >*</span>     
                        {% endif %}             
                    </label>
                    {{ field }}
                    {% if field.help_text %}            
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                        {{ field.help_text|safe }}
                    </small>   
                    {% endif %}               
                  </div> 
                  {% endfor %}           
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                        {% if is_edit %}
                          Сохранить
                        {% else %}
                          Добавить
                        {% endif %}               
                      </button> 
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock %} 

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %} Пост {{ post.text|truncatechars:30 }} {% endblock %}

{% block content %}
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
{% if post.group %}   
    <li class="list-group-item">
       Группа: {{ post.group.title }}
        <a href="{% url 'posts:group_list' post.group.slug %}"> все записи группы </a>
    </li>
{% endif %} 
            <li class="list-group-item">
              Автор: {{ user.username }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span > {{ posts_count }} </span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author.username %}">
                все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          <p> {{ post.text }} </p>
        {% if user ==  post.author %}
          <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
            Редактировать пост
          </a>
        {% endif %}
        </article>
      </div> 
{% endblock %} 

yatube/templates/posts/profile.html
{% extends 'base.html' %}


{% block title %} Профайл пользователя {{ user.username }} {% endblock %}

{% block content %}
    <main>
      <div class="container py-5">        
        <h1>Все посты пользователя {{ user.username }} </h1>
        <h3>Всего постов: {{ posts_count }} </h3>   
{% for post in page_obj %} 
        <article>
          <ul>
            <li>
              Автор: {{ user.username }}
              <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          <p> {{ post.text }} </p>
          <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
        </article>       
{% if post.group %}   
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
{% endif %}    
{% if not forloop.last %}<hr>{% endif %}    
{% endfor %}
        <!-- Остальные посты. после последнего нет черты -->
        <!-- Здесь подключён паджинатор -->  
{% include 'includes/paginator.html' %}
      </div>
    </main>
{% endblock %} 

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %} 

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %} 

yatube/templates/users/password_change_done.html
{% extends "base.html" %}
{% block title %}Пароль изменён{% endblock %}

{% block content %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Пароль изменён
        </div>
        <div class="card-body"> 
          <p>Пароль изменён успешно</p>
        </div> 
      </div> 
    </div> 
  </div> 
</div>
{% endblock %} 

yatube/templates/users/password_change_form.html
{% extends "base.html" %}
{% block title %}Изменение пароля{% endblock %}

{% block content %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Изменить пароль
        </div>
        <div class="card-body">
          <form method="post"> {% csrf_token %}
            <div class="form-group row my-3 p-3">
              <label for="id_old_password">
                Старый пароль
                <span class="required text-danger">*</span>
              </label>    
              <input type="password" name="old_password" autofocus class="form-control" required id="id_old_password">
            </div>
            <div class="form-group row my-3 p-3">
              <label for="id_new_password1">
                Новый пароль
                <span class="required text-danger">*</span>
              </label>    
              <input type="password" name="new_password1" class="form-control" required id="id_new_password1">
                <small id="id_new_password1-help" class="form-text text-muted">
                  <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                </small>
            </div>
            <div class="form-group row my-3 p-3">
              <label for="id_new_password2">
                Подтверждение нового пароля
                <span class="required text-danger">*</span>
              </label>    
              <input type="password" name="new_password2" class="form-control" required id="id_new_password2">
            </div>
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Изменить пароль
              </button>
            </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
</div>

{% endblock %} 

yatube/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Сброс пароля прошёл успешно{% endblock %}

{% block content %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Восстановление пароля завершено
        </div>
        <div class="card-body">
          <p>Ваш пароль был сохранен. Используйте его для входа</p>
          <a href="{% url 'users:login' %}" class="btn btn-link"> Войти</a>
        </div> 
      </div> 
    </div>
  </div> 
</div>
{% endblock %} 

yatube/templates/users/password_reset_done.html
{% extends "base.html" %}
{% block title %}Сброс пароля прошёл успешно{% endblock %}

{% block content %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Отправлено письмо
        </div>
        <div class="card-body">
          <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля</p>
        </div> 
      </div> 
    </div>
  </div> 
</div>
{% endblock %} 

yatube/templates/users/password_reset_form.html
{% extends "base.html" %}
{% block title %}Сброс пароля{% endblock %}

{% block content %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
        </div>
        <div class="card-body"> 
          <form method="post" action="{% url 'users:password_reset_form' %}">{% csrf_token %}
            <div class="form-group row my-3 p-3">
              <label for="id_email">
                Адрес электронной почты
                <span class="required text-danger">*</span>
              </label>    
              <input type="email" name="email" maxlength="254" class="form-control" required id="id_email">
            </div>
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Сбросить пароль
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>  
</div>
{% endblock %} 

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
          {% load user_filters %} {# Загружаем фильтры #}
              {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}

              <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}

              
              {% for field in form %} 
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                
                  {{ field|addclass:'form-control' }} 
                    {% if field.help_text %}
                      <small 
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %} 